baseURL = 'https://grizzlyblog.pages.dev/'
theme = 'PaperMod'
languageCode = 'zh-CN'
title = 'My Blog'

[params]
  customCSS = ["css/custom.css"]
  
  [params.profileMode]
    enabled = true
    title = "㌍㌫㌶㌫㌶"
    subtitle = "Per aspera ad astra."
    imageUrl = "/images/avatar.jpg"
    imageTitle = "头像"
    imageWidth = 150
    imageHeight = 150
    # 你现有的其他配置...
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    # 搜索相关
    searchHidden = false
    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/black123707"
  [[params.socialIcons]]
    name = "bilibili"
    url = "https://space.bilibili.com/520208446?spm_id_from=333.1007.0.0"
  [[params.socialIcons]]
    name = "xiaohongshu"
    url = "https://www.xiaohongshu.com/user/profile/5e9e755200000000010017e8"
    
  [[params.profileMode.buttons]]
    name = "My Blog"
    url = "/posts" 
  [[params.profileMode.buttons]]
    name = "关于网站"
    url = "/about"

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  threshold = 0.4
  location = 0
  distance = 1000
  minMatchCharLength = 2
  keys = ["title", "summary", "content"]

[minify]
  disableXML = true

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20

[[menu.main]]
  identifier = "write"
  name = "Write"
  url = "/admin/"
  weight = 30
  [menu.main.params]
    class = "write-btn"







