baseURL = 'https://grizzlyblog.pages.dev/'
theme = 'PaperMod'
languageCode = 'zh-CN'
title = 'My Blog'

[params]
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true 
  ShowToc = true
  TocOpen = false
  ShowReadingTime = true
  ShowWordCount = true
  ShowLastMod = true
  ShowBreadCrumbs = true
  searchHidden = true
  assets.disableFingerprinting = true
  
  [params.profileMode]
    enabled = true
    title = "㌍㌫㌶㌫㌶"
    subtitle = "Per aspera ad astra."
    imageUrl = "/images/avatar.webp"
    imageTitle = "头像"
    imageWidth = 150
    imageHeight = 150
    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/black123707"
    
  [[params.socialIcons]]
    name = "bilibili"
    url = "https://space.bilibili.com/520208446?spm_id_from=333.40164.0.0"

  [[params.socialIcons]]
    name = "zhihu"
    url = "https://www.zhihu.com/people/764168"
    
  [[params.profileMode.buttons]]
    name = "My Blog"
    url = "/posts" 
  [[params.profileMode.buttons]]
    name = "关于网站"
    url = "/about"

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  threshold = 0.4
  location = 0
  distance = 1000
  minMatchCharLength = 2
  keys = ["title", "summary", "content"]

[[menu.main]]
  identifier = "search"
  name = "🔍"
  url = "/search/"
  weight = 5

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "memos"
  name = "Memos"
  url = "/memos/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 25

[[menu.main]]
  identifier = "write"
  name = "Write"
  url = "/admin/"
  weight = 30
  [menu.main.params]
    class = "write-btn"

[taxonomies]
  tag = "tags"
  category = "categories"
  
[markup]
  [markup.highlight]
    noClasses = false
    lineNumbersInTable = false

[imaging]
  quality = 85
  resampleFilter = "lanczos"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false

outputs:
  home:
    - HTML
    - RSS
    - JSON  # 这行必须有！
