baseURL = 'https://grizzlyblog.pages.dev/'
theme = 'PaperMod'
languageCode = 'zh-CN'
title = 'My Blog'

[params]
  [params.profileMode]
    enabled = true
    title = "㌍㌫㌶㌫㌶"
    subtitle = "Per aspera ad astra."
    imageUrl = "/images/avatar.jpg"
    imageTitle = "头像"
    imageWidth = 150
    imageHeight = 150
    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/black123707"
  [[params.socialIcons]]
    name = "bilibili"
    url = "https://space.bilibili.com/520208446?spm_id_from=333.1007.0.0"
  [[params.socialIcons]]
    name = "xiaohongshu.com"
    url = "https://www.xiaohongshu.com/user/profile/5e9e755200000000010017e8"
  customCSS = ["css/custom.css"]
    
  [[params.profileMode.buttons]]
      name = "My Blog"
      url = "/posts" 
  [[params.profileMode.buttons]]
      name = "关于网站"
      url = "/about"

[minify]
  disableXML = true

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20
